[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver2"
version = "1.2.0"
update_changelog_on_bump = true
version_files = [
	"build.gradle.kts:version"
]
